### ISSUE TITLE
request contact to implement fanet protocol

### ISSUE THREAD

**Issue by DRIZO** [3s1d/fanet-stm32#12]
Hello Juergen,
What is the correct way to contact with you or fanet protocol developer?
I interested on implementation of fanet protocol in our devices.
Thanks

**Comment by 3s1d** [comment]
Hi Drizo,

you can ask me anything here, or use my mail address:
[secondWordOfYourText-aka-myFirstName] [at] skytraxx [dot] eu

Cheers,
Juergen
