### ISSUE TITLE
Flarm licence renewal

### ISSUE THREAD

**Issue by kolupaev** [3s1d/fanet-stm32#18]
Hi @3s1d 

I am trying to update fanet/flarm chip in https://github.com/fhorinek/BB to the latest, as FLARM has expired. 

I believe it is standard skytraxx. Could you share latest flarm.xlb, or what is a reliable source of new builds for the chip? 

Thank you!

**Comment by kolupaev** [comment]
Ah, looks like authors got it!
https://github.com/fhorinek/BB/commit/66bf37abde9cb99405e84d7cfbc96af534da0a4a

For home builds, is there an official source for the new firmware?

**Comment by 3s1d** [comment]
Hi,

sure, go to: https://www.skytraxx.eu/download-3-0
and download the FANET/FLARM update.

Bests,
Juergen
