### ISSUE TITLE
fanet Bodenstation

### ISSUE THREAD

**Issue by wysi** [3s1d/fanet-stm32#3]
Guten Tag

Vielen Dank, dass du/ihr/skytraxx euch dafür entschieden habt, fanet opensource zu machen.
Mir ist bekannt, dass skytraxx im Sommer einen fanet Bodenstation herausgeben wird.

Mich würde folgendes zum Thema Bodenstation interessieren:

Ist vorgesehen, dass darüber neben Wetterdaten auch die Daten von open glider net über fanet and die skytraxx Geräte gesendet werden?
Damit kann man umgehen, dass eine Mobilfunkverbindung/Wifi Hotspot benötigt wird um die Daten von Nicht-Fanet Geräten auf dem skytraxx anzuzeigen.

Ich stelle mir vor, dass ich z.B. mit einem Raspberry Pi als Bodenstation die ONG Datenbank nach Einträgen im Umkreis von einigen Kilometern scanne und die Daten von Nicht-Fanet Geräten (Reine FLARM, Segelflieger, Flugzeuge) über ein LoRa Modul und das Fanet Protokoll an die skytraxx Geräte sende.

Diese skytraxx Geräte hätten somit alle ONG Daten ohne direkt Mobilfunkverbindung/Internet auf dem Bildschirm.

**Comment by 3s1d** [comment]
Hallo wysi,

dein Vorschalg schwebt mir auch schon laenger im Kopf herum. Theoretisch waere es moeglich und ich wuerde das Protokoll dementsprechend erweitern wenn es umgesetzt werden soll.

Derzeit bin ich am kaempfen das Basisstationen FANET daten an OGN Server, also so wie ein Skytraxx 3.0 mit WLAN, weiterleiten. Da wir nicht alles alleine machen wollen versuche ich moeglichst viele Partner ins Boot zu holen und diese gilt es zunaechst zu ueberzeugen.

Viele Gruesse
Juergen

TL;DR: Theoretisch ja, prakitsch wird es noch etwas dauern.
