### ISSUE TITLE
code licensing

### ISSUE THREAD

**Issue by goflyinstruments** [3s1d/fanet-stm32#6]
Hi,
I am working on teamflying feature for my instruments, and compatibility with Fanet would be great part of my product. Some customers pointed me to Fanet months ago. I was trying to find licensing information for this code but I'm not able to find anything. Please let me know if it can be used for commercial product.
Regards
Jarek
GoFly Instruments

**Comment by 3s1d** [comment]
Hi Jarek,

you can do what every you like with it. This as well holds for commercial products. The idea is 'share alike'. We would appreciate if you document what you have done/implemented and let other know. And if you need some changes to the protocol it would be great if you do this in consultation with me.

Cheers,
Juergen

**Comment by scottyob** [comment]
You should probably consider adding a license.  It *looks like* this code is being used in the GxAirCom tool, and I'd also like to use it, but having a license associated with it would be a good thing.

What you're asking here re changes kind of sounds like a GPLv3 license?

**Comment by 3s1d** [comment]
Hi,

frankly, I know a hand full of companies using this code already (can tell as there WAS a bug in it and i could trigger it). But so far I haven't seen many republishing it... oh well, I am realistic, a license would not change much here. So just use it, please be careful what you do to the network. That't fine with me.

Bests,
Juergen

**Comment by scottyob** [comment]
> Hi,
> 
> frankly, I know a hand full of companies using this code already (can tell as there WAS a bug in it and i could trigger it). But so far I haven't seen many republishing it... oh well, I am realistic, a license would not change much here. So just use it, please be careful what you do to the network. That't fine with me.
> 
> Bests, Juergen

I'm looking at implementing a Fanet feature in a [vario I'm working on](https://leafvario.com/)  I'd love to use this code as a starting point.

Mind if I try to copy/paste a lot of it into a new Github repo and build an Arduino/PlatformIO library around it to have a Fanet library that myself and others can just import and use?  It sounds like we're on the same boat, an MIT license (do what you want with it, just don't sue) is appropriate here?  I'd attribute you as the original author in this repo.

**Comment by 3s1d** [comment]
Nice! Go ahead. The code is pretty stable and should not see much changes any more (despite of not packet types).

I just made opened a new issue on your repo, please answer it. Thanks :)
