### ISSUE TITLE
Seek help

### ISSUE THREAD

**Issue by z983889767** [3s1d/fanet-stm32#8]
Excuse me, is this code developed with cubeide? Why does the problem arise when building a project：
make clean 
make: *** No rule to make target 'clean'.  Stop.
"make clean" terminated with exit code 2. Build might be incomplete.
And the ioc file can't be opened
Please help to solve these problems
![image](https://user-images.githubusercontent.com/64945286/81256344-cab0ca80-9062-11ea-892b-928e9c856647.png)

**Comment by 3s1d** [comment]
Hi,

I am using sw4stm32 from AC6 (https://www.openstm32.org). If you are using a different IDE you have to manually adjust the project files.

Cheers,
Juergen
