### ISSUE TITLE
question

### ISSUE THREAD

**Issue by z983889767** [3s1d/fanet-stm32#9]
What kind of routing protocol does fanet use
and What is the framework of ad hoc network？

**Comment by 3s1d** [comment]
Hi,
I am not sure what your background is and how to point you into the right direction. Maybe so much:
FANET does not yet has a complex/complete routing theme in regard to a classic transportation protocol. As it's designed for a highly mobile 3D aerial system. It can do 1-hop packet forwarding using certain criteria (see mac layer). 

Cheers,
Juergen
